//action types
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SUBMIT_USER_STATS = 'SUBMIT_USER_STATS';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const FETCH_FOOD_DIARY = 'FETCH_USER_DIARY';
export const SUBMIT_DIARY_ENTRY = 'SUBMIT_DIARY_ENTRY';
export const PW_DOES_NOT_MATCH = 'PW_DOES_NOT_MATCH';
export const FETCH_ALL_GROUPS = 'FETCH_ALL_GROUPS';
export const FETCH_USER_GROUPS = 'FETCH_USER_GROUPS';
export const CREATE_NEW_GROUP = 'CREATE_NEW_GROUP';
export const TOGGLE_EDITING = 'TOGGLE_EDITING';
export const DELETE_DIARY_ENTRY = 'DELETE_DIARY_ENTRY';
export const LEAVE_GROUP = 'LEAVE_GROUP';
export const JOIN_GROUP = 'JOIN_GROUP';
export const FETCH_IDEAL_MACROS = 'FETCH_IDEAL_MACROS';
export const FETCH_ACTUAL_MACROS = 'FETCH_ACTUAL_MACROS';
